### ISSUE TITLE
scalastyle-maven-plugin support

### ISSUE THREAD

**Issue by kenniy** [beautiful-scala/scalastyle#137]
Thanks for keeping a fork of scalastyle updated. Can we have support for [maven-plugin](scalastyle-maven-plugin ) if possible?
If there is any additional work item required, I can put together a PR once the project is created. Thanks!

**Comment by mwz** [comment]
Hi @kenniy, maintaining a maven plugin isn't something that's in my plans, but feel free to link to the project on the [website](https://github.com/beautiful-scala/scalastyle-website) if you decide to maintain the fork yourself.
